#!/bin/bash
####################################################################################
###
### QUBIC miner for ton.ninja
### os.dog integration: shatll(@osdog)
###
####################################################################################

#   example
#
#	{
#		"miner":"lolminer",
#		"algo":"nexapow",
#		"online":"1707474764",
#		"total_hr":"71842910",
#		"total_share":"1",
#		"total_badshare":"0",
#		"ver":"1.82a",
#		"hr":[11580000,27740000,0,0,2990000,0,22650000,6880000],
#		"share":[0,1,0,0,0,0,0,0],
#		"badshare":[0,0,0,0,0,0,0,0],
#		"invshare":[0,0,0,0,0,0,0,0],
#		"busid":["03","05","06","07","09","0b","0c","0d"],
#		"coin":"NEXA"
#		"temp":[31,28,29,29,31,29,30,30],     #  unnecessary field if 'busid' is provided
#		"temp2":[38,35,35,35,37,34,37,37],    #  unnecessary field if 'busid' is provided
#		"temp3":[0,0,0,0,0,0,0,0],            #  unnecessary field if 'busid' is provided
#		"fan":[45,45,44,45,44,44,45,46],      #  unnecessary field if 'busid' is provided
#	}


baseDir=`dirname $0`


LOG="/dog/log/qubic-cpu.log"

algo="qubic"
miner="qli-Client"

ver=`$baseDir/qli-Client --version | sed 's/Client Version //'`
[[ ! $ver ]] && ver='unknown'

data=$(
		jq -n \
    --arg algo "$algo" \
    --arg miner "$miner" \
		'{
			$miner,
			$algo
		}'
)
minername="qli-runner"
online_raw=`ps -C $minername -o etimes= | awk '{print $1}' | tail -n 1`
if [[ ! -z $online_raw ]]; then
  online=$(date --date "-$online_raw sec" +%s) #absolute time
  data=`jq ". += {\"online\": $online}" <<< "$data"`
fi

allGpuHrStr=`tail -n 20 $LOG | grep SOL: | grep -Ev "Solution|argument|devices" | tail -n 1`

hr_json=[]
totalHr=0

for (( i=0; i < 1; i++ )); do
  hr=`echo $allGpuHrStr | sed -e 's/avg .*//; s/.* | \([.0-9a-zA-Z]*\) it\/s.*/\1/'`
  hr_json=`jq ". += [$hr]" <<< "$hr_json"`
  totalHr=`echo "$totalHr + $hr" | bc`
done

if [[ ! -z $hr_json ]]; then
  data=`jq ". += {\"hr\": $hr_json}" <<< "$data"`
  data=`jq ". += {\"total_hr\": $totalHr}" <<< "$data"`
fi

allStatstr=`tail -n 20 $LOG | grep SOL: | tail -n 1`
totalSolutions=`echo $allStatstr | sed -e 's/.*SOL: //; s#/.*##'`
if [[ ! -z $totalSolutions ]]; then
  data=`jq ". += {\"total_share\": $totalSolutions}" <<< "$data"`
fi

epoch=`echo $allStatstr | sed -e 's/.*E://; s# .*##'`
[[ $epoch ]] && ver="$ver|E${epoch}"
data=`jq ". += {\"ver\": \"$ver\"}" <<< "$data"`

#   finally return json data
echo "$data" | jq -c
